title: Newer York
description: Meet Newer York, a city that's much newer than New York
favicon: "ilovenny.svg"
github:
  is_project_page: false
permalink: /:slug

remote_theme: pages-themes/slate
plugins:
- jekyll-remote-theme
