title: Uranio
description: Meet Uranio, a city that has transitioned to nuclear energy
url: https://sam-wong8.github.io/uranio/
permalink: /:slug

remote_theme: pages-themes/cayman
plugins:
- jekyll-remote-theme
