title: Uranio
description: Meet Uranio, a city that has transitioned to nuclear energy
github:
  is_project_page: false
permalink: /:slug

remote_theme: LeNPaul/Millennial
plugins:
- jekyll-remote-theme
